
import React from 'react'
import dynamic from 'next/dynamic';

const MyClientComponent = dynamic(() => import('../../../components/Admin/Pages/Managemembe/Mycomponent'), {
  ssr: false, // Treat this component as a "Client Component"
});

export const metadata = {
  title: "จัดการสมาชิก",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <MyClientComponent />
  )
}

export default page