import React from 'react'
import dynamic from 'next/dynamic';

const MyClientComponent = dynamic(() => import('../../../components/Creator/Pages/CreateContent/MyComponent'), {
  ssr: false, // Treat this component as a "Client Component"
});
export const metadata = {
  title: "สร้างผลงาน",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <MyClientComponent/>
  )
}

export default page