import React from 'react'
import dynamic from 'next/dynamic';

const MyClientComponent = dynamic(() => import('../../components/Admin/Pages/Dashboard/MyComponent'));

export const metadata = {
  title: "ภาพรวม",
  description: "Generated by create next app",
};
const Page = () => {
  return (
   <MyClientComponent />
  )
}


export default Page